services:
  - type: web
    plan: free
    name: Hokage Bot 🤖
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y libgl1 libglib2.0-0 libsm6 libxext6 libxrender-dev && \
      pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/vincentkaleba/Hokage-bot-1.0.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEB_SUPPORT
        sync: false
